In [5]:
import torch

In [10]:
scalar = torch.tensor(7)
print(type(scalar))
print(scalar.item())
print(scalar.ndim)

<class 'torch.Tensor'>
7
0


In [15]:
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [18]:
matrix = torch.tensor([[7,8,5] , [1,2,4]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[7, 8, 5],
        [1, 2, 4]])
2
torch.Size([2, 3])


In [19]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [29]:
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.1754, 0.5700, 0.4949, 0.2551],
        [0.2661, 0.8029, 0.8233, 0.7658],
        [0.2057, 0.6925, 0.2846, 0.8876]])
2


In [33]:
rand_img_tensor = torch.rand(size = (224,224,3))
print(rand_img_tensor)

tensor([[[0.4159, 0.2588, 0.9764],
         [0.2280, 0.6349, 0.5270],
         [0.5395, 0.8138, 0.5283],
         ...,
         [0.1800, 0.0440, 0.4868],
         [0.3261, 0.7912, 0.4468],
         [0.4264, 0.3453, 0.4834]],

        [[0.3957, 0.5731, 0.8699],
         [0.8431, 0.1646, 0.6333],
         [0.6580, 0.6810, 0.3859],
         ...,
         [0.3961, 0.3483, 0.0548],
         [0.8764, 0.7037, 0.4850],
         [0.6936, 0.3752, 0.5011]],

        [[0.0578, 0.5674, 0.9395],
         [0.8870, 0.4995, 0.8182],
         [0.7147, 0.0120, 0.0184],
         ...,
         [0.9792, 0.9677, 0.6654],
         [0.1866, 0.4715, 0.1552],
         [0.7101, 0.6224, 0.3397]],

        ...,

        [[0.3883, 0.2973, 0.1984],
         [0.6261, 0.0897, 0.4702],
         [0.7058, 0.8709, 0.5402],
         ...,
         [0.6888, 0.5931, 0.7585],
         [0.7545, 0.1495, 0.4116],
         [0.4885, 0.2133, 0.3949]],

        [[0.5911, 0.4688, 0.8606],
         [0.4303, 0.2298, 0.1899],
         [0.

In [37]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
tensor1 = torch.tensor([1,2,3])

print(torch.matmul(tensor1,tensor1))

tensor(14)


In [47]:
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor = torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [50]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')